//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PAR2022.pso /Fcshaderdump19/PAR2022.pso.dis
//
//
// Parameters:
//
sampler2D TESR_samplerBaseMap : register(s0) = sampler_state { MINFILTER = LINEAR; };
float4 Toggles : register(c7);

//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Toggles      const_7       1
//   BaseMap      texture_0       1
//


// Structures:

struct VS_OUTPUT {
    float2 BaseUV : TEXCOORD0;
    float3 texcoord_6 : TEXCOORD6_centroid;
    float3 color_0 : COLOR0;
    float4 ShadowUV0 : TEXCOORD4;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:


PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	uvtile(w)		(((w) * 0.04) - 0.02)

    float4 r0;
    float2 uv0;
    float Shadow;

    Shadow = 1.0f;

    r0.xyzw = tex2D(TESR_samplerBaseMap, IN.BaseUV.xy);			// partial precision
    uv0.xy = (uvtile(r0.w) * (IN.texcoord_6.xy / length(IN.texcoord_6.xyz))) + IN.BaseUV.xy;
    r0.xyzw = tex2D(TESR_samplerBaseMap, uv0.xy);			// partial precision
    OUT.color_0.a = 1;			// partial precision
    OUT.color_0.rgb = (Toggles.x <= 0.0 ? r0.xyz * Shadow : (r0.xyz * IN.color_0.rgb)) * Shadow;

    return OUT;
};

// approximately 11 instruction slots used (2 texture, 9 arithmetic)
